import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_events_origin" AS ENUM('ccm', 'external');
  ALTER TYPE "public"."enum_regional_communities_blocks_community_header__gfrato" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_hero1_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_hero2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_section_header_ch_bd3iha" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_split_row_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_carousel1_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_timeline_row_chap_1eegxe5" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_faqs_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_content_feed_chap_1rge6pj" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_events_calendar_c_13ygnl9" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_people_widget_cha_1659sat" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_grid_row_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_region_map_chapte_1yk15pm" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_atlas_embed_chapt_25dfli" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_cta1_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_submit_story_bann_1ykpwzu" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_form_newsletter_c_14z7pw5" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_logo_cloud1_chapt_no9yx1" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_carousel2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_community_members_t33wpu" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_community_header__1y3gsh7" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_hero1_2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_hero2_2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_section_header_2__gedkgd" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_split_row_2_chapt_1scenwj" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_carousel1_2_chapt_cauxwd" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_timeline_row_2_ch_l9so6y" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_faqs_2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_content_feed_2_ch_yh1ub8" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_events_calendar_2_1yhfz4q" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_people_widget_2_c_11urcg2" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_grid_row_2_chapte_b6t8tv" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_region_map_2_chap_1khqxi9" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_atlas_embed_2_cha_1qp5bad" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_cta1_2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_submit_story_bann_k0twxt" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_form_newsletter_2_11nvtoy" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_logo_cloud1_2_cha_1v49s1u" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_carousel2_2_chapt_hii4za" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum_regional_communities_blocks_community_members_1owqk15" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_community_head_z9koa" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_hero1_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_hero2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_section_header_12xzwqo" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_split_row_chap_1ykuzke" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_carousel1_chap_14nx26c" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_timeline_row_c_pvpskr" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_faqs_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_content_feed_c_wbxj9d" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_events_calenda_9o9sg7" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_people_widget__baoh03" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_grid_row_chapt_1t88e8u" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_region_map_cha_xvdpkw" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_ch_17s1ah4" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_cta1_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_zwdst0" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_form_newslette_s3biab" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_ch_jtm3wj" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_carousel2_chap_1jh0a0j" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_community_memb_1v441c4" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_community_head_5st7xd" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_hero1_2_chapte_1t5ygvh" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_hero2_2_chapte_k3pmiu" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_section_header_unitpz" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_split_row_2_ch_1cab6h9" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_carousel1_2_ch_hbqyvn" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_timeline_row_2_urw8y8" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_faqs_2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_content_feed_2_1gu2ali" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_events_calenda_bavpvo" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_people_widget__1ucyr60" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_grid_row_2_cha_1lo9grh" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_region_map_2_c_1als5o7" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_2__13fttjj" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_cta1_2_chapter_chapter_kind" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_1kwp65f" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_form_newslette_on6v9k" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_2__1g5s77c" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_carousel2_2_ch_18ei82w" ADD VALUE 'events' BEFORE 'voices';
  ALTER TYPE "public"."enum__regional_communities_v_blocks_community_memb_16accr7" ADD VALUE 'events' BEFORE 'voices';
  CREATE TABLE "events_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" varchar NOT NULL,
  	"path" varchar NOT NULL,
  	"tags_id" varchar
  );
  
  CREATE TABLE "event_suggestions_blocked" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"user_id" varchar NOT NULL,
  	"note" varchar
  );
  
  CREATE TABLE "event_suggestions" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"open" boolean DEFAULT true,
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  ALTER TABLE "events" ADD COLUMN "origin" "enum_events_origin" DEFAULT 'ccm';
  ALTER TABLE "events" ADD COLUMN "organiser_id" varchar;
  ALTER TABLE "events" ADD COLUMN "organiser_name" varchar;
  ALTER TABLE "events" ADD COLUMN "notified_status" varchar;
  ALTER TABLE "events_rels" ADD CONSTRAINT "events_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "events_rels" ADD CONSTRAINT "events_rels_tags_fk" FOREIGN KEY ("tags_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "event_suggestions_blocked" ADD CONSTRAINT "event_suggestions_blocked_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."event_suggestions"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "events_rels_order_idx" ON "events_rels" USING btree ("order");
  CREATE INDEX "events_rels_parent_idx" ON "events_rels" USING btree ("parent_id");
  CREATE INDEX "events_rels_path_idx" ON "events_rels" USING btree ("path");
  CREATE INDEX "events_rels_tags_id_idx" ON "events_rels" USING btree ("tags_id");
  CREATE INDEX "event_suggestions_blocked_order_idx" ON "event_suggestions_blocked" USING btree ("_order");
  CREATE INDEX "event_suggestions_blocked_parent_id_idx" ON "event_suggestions_blocked" USING btree ("_parent_id");
  ALTER TABLE "events" ADD CONSTRAINT "events_organiser_id_organizations_id_fk" FOREIGN KEY ("organiser_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "events_organiser_idx" ON "events" USING btree ("organiser_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "events_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "event_suggestions_blocked" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "event_suggestions" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "events_rels" CASCADE;
  DROP TABLE "event_suggestions_blocked" CASCADE;
  DROP TABLE "event_suggestions" CASCADE;
  ALTER TABLE "events" DROP CONSTRAINT "events_organiser_id_organizations_id_fk";
  
  ALTER TABLE "regional_communities_blocks_community_header" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_community_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_community_header__gfrato";
  CREATE TYPE "public"."enum_regional_communities_blocks_community_header__gfrato" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_community_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_community_header__gfrato";
  ALTER TABLE "regional_communities_blocks_community_header" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_community_header__gfrato" USING "chapter_kind"::"public"."enum_regional_communities_blocks_community_header__gfrato";
  ALTER TABLE "regional_communities_blocks_hero1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_hero1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_hero1_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_hero1_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_hero1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_hero1_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_hero1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_hero1_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_hero1_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_hero2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_hero2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_hero2_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_hero2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_hero2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_hero2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_hero2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_hero2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_hero2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_section_header" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_section_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_section_header_ch_bd3iha";
  CREATE TYPE "public"."enum_regional_communities_blocks_section_header_ch_bd3iha" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_section_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_section_header_ch_bd3iha";
  ALTER TABLE "regional_communities_blocks_section_header" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_section_header_ch_bd3iha" USING "chapter_kind"::"public"."enum_regional_communities_blocks_section_header_ch_bd3iha";
  ALTER TABLE "regional_communities_blocks_split_row" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_split_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_split_row_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_split_row_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_split_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_split_row_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_split_row" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_split_row_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_split_row_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_carousel1_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_carousel1_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_carousel1_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_carousel1_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_carousel1_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_timeline_row_chap_1eegxe5";
  CREATE TYPE "public"."enum_regional_communities_blocks_timeline_row_chap_1eegxe5" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_timeline_row_chap_1eegxe5";
  ALTER TABLE "regional_communities_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_timeline_row_chap_1eegxe5" USING "chapter_kind"::"public"."enum_regional_communities_blocks_timeline_row_chap_1eegxe5";
  ALTER TABLE "regional_communities_blocks_faqs" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_faqs" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_faqs_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_faqs_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_faqs" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_faqs_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_faqs" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_faqs_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_faqs_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_content_feed_chap_1rge6pj";
  CREATE TYPE "public"."enum_regional_communities_blocks_content_feed_chap_1rge6pj" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_content_feed_chap_1rge6pj";
  ALTER TABLE "regional_communities_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_content_feed_chap_1rge6pj" USING "chapter_kind"::"public"."enum_regional_communities_blocks_content_feed_chap_1rge6pj";
  ALTER TABLE "regional_communities_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_events_calendar_c_13ygnl9";
  CREATE TYPE "public"."enum_regional_communities_blocks_events_calendar_c_13ygnl9" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_events_calendar_c_13ygnl9";
  ALTER TABLE "regional_communities_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_events_calendar_c_13ygnl9" USING "chapter_kind"::"public"."enum_regional_communities_blocks_events_calendar_c_13ygnl9";
  ALTER TABLE "regional_communities_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_people_widget_cha_1659sat";
  CREATE TYPE "public"."enum_regional_communities_blocks_people_widget_cha_1659sat" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_people_widget_cha_1659sat";
  ALTER TABLE "regional_communities_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_people_widget_cha_1659sat" USING "chapter_kind"::"public"."enum_regional_communities_blocks_people_widget_cha_1659sat";
  ALTER TABLE "regional_communities_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_grid_row_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_grid_row_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_grid_row_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_grid_row_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_grid_row_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_region_map" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_region_map" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_region_map_chapte_1yk15pm";
  CREATE TYPE "public"."enum_regional_communities_blocks_region_map_chapte_1yk15pm" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_region_map" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_region_map_chapte_1yk15pm";
  ALTER TABLE "regional_communities_blocks_region_map" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_region_map_chapte_1yk15pm" USING "chapter_kind"::"public"."enum_regional_communities_blocks_region_map_chapte_1yk15pm";
  ALTER TABLE "regional_communities_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_atlas_embed_chapt_25dfli";
  CREATE TYPE "public"."enum_regional_communities_blocks_atlas_embed_chapt_25dfli" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_atlas_embed_chapt_25dfli";
  ALTER TABLE "regional_communities_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_atlas_embed_chapt_25dfli" USING "chapter_kind"::"public"."enum_regional_communities_blocks_atlas_embed_chapt_25dfli";
  ALTER TABLE "regional_communities_blocks_cta1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_cta1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_cta1_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_cta1_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_cta1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_cta1_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_cta1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_cta1_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_cta1_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_submit_story_bann_1ykpwzu";
  CREATE TYPE "public"."enum_regional_communities_blocks_submit_story_bann_1ykpwzu" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_submit_story_bann_1ykpwzu";
  ALTER TABLE "regional_communities_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_submit_story_bann_1ykpwzu" USING "chapter_kind"::"public"."enum_regional_communities_blocks_submit_story_bann_1ykpwzu";
  ALTER TABLE "regional_communities_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_form_newsletter_c_14z7pw5";
  CREATE TYPE "public"."enum_regional_communities_blocks_form_newsletter_c_14z7pw5" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_form_newsletter_c_14z7pw5";
  ALTER TABLE "regional_communities_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_form_newsletter_c_14z7pw5" USING "chapter_kind"::"public"."enum_regional_communities_blocks_form_newsletter_c_14z7pw5";
  ALTER TABLE "regional_communities_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_logo_cloud1_chapt_no9yx1";
  CREATE TYPE "public"."enum_regional_communities_blocks_logo_cloud1_chapt_no9yx1" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_logo_cloud1_chapt_no9yx1";
  ALTER TABLE "regional_communities_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_logo_cloud1_chapt_no9yx1" USING "chapter_kind"::"public"."enum_regional_communities_blocks_logo_cloud1_chapt_no9yx1";
  ALTER TABLE "regional_communities_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_carousel2_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_carousel2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_carousel2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_carousel2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_carousel2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_community_members" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_community_members" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_community_members_t33wpu";
  CREATE TYPE "public"."enum_regional_communities_blocks_community_members_t33wpu" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_community_members" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_community_members_t33wpu";
  ALTER TABLE "regional_communities_blocks_community_members" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_community_members_t33wpu" USING "chapter_kind"::"public"."enum_regional_communities_blocks_community_members_t33wpu";
  ALTER TABLE "regional_communities_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_community_header__1y3gsh7";
  CREATE TYPE "public"."enum_regional_communities_blocks_community_header__1y3gsh7" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_community_header__1y3gsh7";
  ALTER TABLE "regional_communities_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_community_header__1y3gsh7" USING "chapter_kind"::"public"."enum_regional_communities_blocks_community_header__1y3gsh7";
  ALTER TABLE "regional_communities_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_hero1_2_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_hero1_2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_hero1_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_hero1_2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_hero1_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_hero2_2_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_hero2_2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_hero2_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_hero2_2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_hero2_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_section_header_2__gedkgd";
  CREATE TYPE "public"."enum_regional_communities_blocks_section_header_2__gedkgd" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_section_header_2__gedkgd";
  ALTER TABLE "regional_communities_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_section_header_2__gedkgd" USING "chapter_kind"::"public"."enum_regional_communities_blocks_section_header_2__gedkgd";
  ALTER TABLE "regional_communities_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_split_row_2_chapt_1scenwj";
  CREATE TYPE "public"."enum_regional_communities_blocks_split_row_2_chapt_1scenwj" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_split_row_2_chapt_1scenwj";
  ALTER TABLE "regional_communities_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_split_row_2_chapt_1scenwj" USING "chapter_kind"::"public"."enum_regional_communities_blocks_split_row_2_chapt_1scenwj";
  ALTER TABLE "regional_communities_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_carousel1_2_chapt_cauxwd";
  CREATE TYPE "public"."enum_regional_communities_blocks_carousel1_2_chapt_cauxwd" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_carousel1_2_chapt_cauxwd";
  ALTER TABLE "regional_communities_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_carousel1_2_chapt_cauxwd" USING "chapter_kind"::"public"."enum_regional_communities_blocks_carousel1_2_chapt_cauxwd";
  ALTER TABLE "regional_communities_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_timeline_row_2_ch_l9so6y";
  CREATE TYPE "public"."enum_regional_communities_blocks_timeline_row_2_ch_l9so6y" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_timeline_row_2_ch_l9so6y";
  ALTER TABLE "regional_communities_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_timeline_row_2_ch_l9so6y" USING "chapter_kind"::"public"."enum_regional_communities_blocks_timeline_row_2_ch_l9so6y";
  ALTER TABLE "regional_communities_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_faqs_2_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_faqs_2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_faqs_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_faqs_2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_faqs_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_content_feed_2_ch_yh1ub8";
  CREATE TYPE "public"."enum_regional_communities_blocks_content_feed_2_ch_yh1ub8" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_content_feed_2_ch_yh1ub8";
  ALTER TABLE "regional_communities_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_content_feed_2_ch_yh1ub8" USING "chapter_kind"::"public"."enum_regional_communities_blocks_content_feed_2_ch_yh1ub8";
  ALTER TABLE "regional_communities_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_events_calendar_2_1yhfz4q";
  CREATE TYPE "public"."enum_regional_communities_blocks_events_calendar_2_1yhfz4q" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_events_calendar_2_1yhfz4q";
  ALTER TABLE "regional_communities_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_events_calendar_2_1yhfz4q" USING "chapter_kind"::"public"."enum_regional_communities_blocks_events_calendar_2_1yhfz4q";
  ALTER TABLE "regional_communities_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_people_widget_2_c_11urcg2";
  CREATE TYPE "public"."enum_regional_communities_blocks_people_widget_2_c_11urcg2" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_people_widget_2_c_11urcg2";
  ALTER TABLE "regional_communities_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_people_widget_2_c_11urcg2" USING "chapter_kind"::"public"."enum_regional_communities_blocks_people_widget_2_c_11urcg2";
  ALTER TABLE "regional_communities_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_grid_row_2_chapte_b6t8tv";
  CREATE TYPE "public"."enum_regional_communities_blocks_grid_row_2_chapte_b6t8tv" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_grid_row_2_chapte_b6t8tv";
  ALTER TABLE "regional_communities_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_grid_row_2_chapte_b6t8tv" USING "chapter_kind"::"public"."enum_regional_communities_blocks_grid_row_2_chapte_b6t8tv";
  ALTER TABLE "regional_communities_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_region_map_2_chap_1khqxi9";
  CREATE TYPE "public"."enum_regional_communities_blocks_region_map_2_chap_1khqxi9" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_region_map_2_chap_1khqxi9";
  ALTER TABLE "regional_communities_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_region_map_2_chap_1khqxi9" USING "chapter_kind"::"public"."enum_regional_communities_blocks_region_map_2_chap_1khqxi9";
  ALTER TABLE "regional_communities_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_atlas_embed_2_cha_1qp5bad";
  CREATE TYPE "public"."enum_regional_communities_blocks_atlas_embed_2_cha_1qp5bad" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_atlas_embed_2_cha_1qp5bad";
  ALTER TABLE "regional_communities_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_atlas_embed_2_cha_1qp5bad" USING "chapter_kind"::"public"."enum_regional_communities_blocks_atlas_embed_2_cha_1qp5bad";
  ALTER TABLE "regional_communities_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_cta1_2_chapter_chapter_kind";
  CREATE TYPE "public"."enum_regional_communities_blocks_cta1_2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_cta1_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_cta1_2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum_regional_communities_blocks_cta1_2_chapter_chapter_kind";
  ALTER TABLE "regional_communities_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_submit_story_bann_k0twxt";
  CREATE TYPE "public"."enum_regional_communities_blocks_submit_story_bann_k0twxt" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_submit_story_bann_k0twxt";
  ALTER TABLE "regional_communities_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_submit_story_bann_k0twxt" USING "chapter_kind"::"public"."enum_regional_communities_blocks_submit_story_bann_k0twxt";
  ALTER TABLE "regional_communities_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_form_newsletter_2_11nvtoy";
  CREATE TYPE "public"."enum_regional_communities_blocks_form_newsletter_2_11nvtoy" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_form_newsletter_2_11nvtoy";
  ALTER TABLE "regional_communities_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_form_newsletter_2_11nvtoy" USING "chapter_kind"::"public"."enum_regional_communities_blocks_form_newsletter_2_11nvtoy";
  ALTER TABLE "regional_communities_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_logo_cloud1_2_cha_1v49s1u";
  CREATE TYPE "public"."enum_regional_communities_blocks_logo_cloud1_2_cha_1v49s1u" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_logo_cloud1_2_cha_1v49s1u";
  ALTER TABLE "regional_communities_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_logo_cloud1_2_cha_1v49s1u" USING "chapter_kind"::"public"."enum_regional_communities_blocks_logo_cloud1_2_cha_1v49s1u";
  ALTER TABLE "regional_communities_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_carousel2_2_chapt_hii4za";
  CREATE TYPE "public"."enum_regional_communities_blocks_carousel2_2_chapt_hii4za" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_carousel2_2_chapt_hii4za";
  ALTER TABLE "regional_communities_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_carousel2_2_chapt_hii4za" USING "chapter_kind"::"public"."enum_regional_communities_blocks_carousel2_2_chapt_hii4za";
  ALTER TABLE "regional_communities_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "regional_communities_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_regional_communities_blocks_community_members_1owqk15";
  CREATE TYPE "public"."enum_regional_communities_blocks_community_members_1owqk15" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "regional_communities_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum_regional_communities_blocks_community_members_1owqk15";
  ALTER TABLE "regional_communities_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum_regional_communities_blocks_community_members_1owqk15" USING "chapter_kind"::"public"."enum_regional_communities_blocks_community_members_1owqk15";
  ALTER TABLE "_regional_communities_v_blocks_community_header" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_community_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_community_head_z9koa";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_community_head_z9koa" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_community_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_community_head_z9koa";
  ALTER TABLE "_regional_communities_v_blocks_community_header" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_community_head_z9koa" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_community_head_z9koa";
  ALTER TABLE "_regional_communities_v_blocks_hero1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_hero1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_hero1_chapter_chapter_kind";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_hero1_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_hero1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_hero1_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_hero1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_hero1_chapter_chapter_kind" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_hero1_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_hero2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_hero2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_hero2_chapter_chapter_kind";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_hero2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_hero2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_hero2_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_hero2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_hero2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_hero2_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_section_header" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_section_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_section_header_12xzwqo";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_section_header_12xzwqo" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_section_header" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_section_header_12xzwqo";
  ALTER TABLE "_regional_communities_v_blocks_section_header" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_section_header_12xzwqo" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_section_header_12xzwqo";
  ALTER TABLE "_regional_communities_v_blocks_split_row" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_split_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_split_row_chap_1ykuzke";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_split_row_chap_1ykuzke" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_split_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_split_row_chap_1ykuzke";
  ALTER TABLE "_regional_communities_v_blocks_split_row" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_split_row_chap_1ykuzke" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_split_row_chap_1ykuzke";
  ALTER TABLE "_regional_communities_v_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_carousel1_chap_14nx26c";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_carousel1_chap_14nx26c" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_carousel1_chap_14nx26c";
  ALTER TABLE "_regional_communities_v_blocks_carousel1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_carousel1_chap_14nx26c" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_carousel1_chap_14nx26c";
  ALTER TABLE "_regional_communities_v_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_timeline_row_c_pvpskr";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_timeline_row_c_pvpskr" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_timeline_row_c_pvpskr";
  ALTER TABLE "_regional_communities_v_blocks_timeline_row" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_timeline_row_c_pvpskr" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_timeline_row_c_pvpskr";
  ALTER TABLE "_regional_communities_v_blocks_faqs" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_faqs" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_faqs_chapter_chapter_kind";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_faqs_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_faqs" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_faqs_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_faqs" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_faqs_chapter_chapter_kind" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_faqs_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_content_feed_c_wbxj9d";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_content_feed_c_wbxj9d" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_content_feed_c_wbxj9d";
  ALTER TABLE "_regional_communities_v_blocks_content_feed" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_content_feed_c_wbxj9d" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_content_feed_c_wbxj9d";
  ALTER TABLE "_regional_communities_v_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_events_calenda_9o9sg7";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_events_calenda_9o9sg7" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_events_calenda_9o9sg7";
  ALTER TABLE "_regional_communities_v_blocks_events_calendar" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_events_calenda_9o9sg7" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_events_calenda_9o9sg7";
  ALTER TABLE "_regional_communities_v_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_people_widget__baoh03";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_people_widget__baoh03" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_people_widget__baoh03";
  ALTER TABLE "_regional_communities_v_blocks_people_widget" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_people_widget__baoh03" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_people_widget__baoh03";
  ALTER TABLE "_regional_communities_v_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_grid_row_chapt_1t88e8u";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_grid_row_chapt_1t88e8u" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_grid_row_chapt_1t88e8u";
  ALTER TABLE "_regional_communities_v_blocks_grid_row" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_grid_row_chapt_1t88e8u" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_grid_row_chapt_1t88e8u";
  ALTER TABLE "_regional_communities_v_blocks_region_map" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_region_map" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_region_map_cha_xvdpkw";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_region_map_cha_xvdpkw" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_region_map" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_region_map_cha_xvdpkw";
  ALTER TABLE "_regional_communities_v_blocks_region_map" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_region_map_cha_xvdpkw" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_region_map_cha_xvdpkw";
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_ch_17s1ah4";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_ch_17s1ah4" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_atlas_embed_ch_17s1ah4";
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_ch_17s1ah4" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_atlas_embed_ch_17s1ah4";
  ALTER TABLE "_regional_communities_v_blocks_cta1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_cta1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_cta1_chapter_chapter_kind";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_cta1_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_cta1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_cta1_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_cta1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_cta1_chapter_chapter_kind" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_cta1_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_zwdst0";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_zwdst0" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_submit_story_b_zwdst0";
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_zwdst0" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_submit_story_b_zwdst0";
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_form_newslette_s3biab";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_form_newslette_s3biab" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_form_newslette_s3biab";
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_form_newslette_s3biab" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_form_newslette_s3biab";
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_ch_jtm3wj";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_ch_jtm3wj" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_logo_cloud1_ch_jtm3wj";
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_ch_jtm3wj" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_logo_cloud1_ch_jtm3wj";
  ALTER TABLE "_regional_communities_v_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_carousel2_chap_1jh0a0j";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_carousel2_chap_1jh0a0j" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_carousel2_chap_1jh0a0j";
  ALTER TABLE "_regional_communities_v_blocks_carousel2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_carousel2_chap_1jh0a0j" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_carousel2_chap_1jh0a0j";
  ALTER TABLE "_regional_communities_v_blocks_community_members" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_community_members" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_community_memb_1v441c4";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_community_memb_1v441c4" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_community_members" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_community_memb_1v441c4";
  ALTER TABLE "_regional_communities_v_blocks_community_members" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_community_memb_1v441c4" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_community_memb_1v441c4";
  ALTER TABLE "_regional_communities_v_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_community_head_5st7xd";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_community_head_5st7xd" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_community_head_5st7xd";
  ALTER TABLE "_regional_communities_v_blocks_community_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_community_head_5st7xd" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_community_head_5st7xd";
  ALTER TABLE "_regional_communities_v_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_hero1_2_chapte_1t5ygvh";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_hero1_2_chapte_1t5ygvh" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_hero1_2_chapte_1t5ygvh";
  ALTER TABLE "_regional_communities_v_blocks_hero1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_hero1_2_chapte_1t5ygvh" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_hero1_2_chapte_1t5ygvh";
  ALTER TABLE "_regional_communities_v_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_hero2_2_chapte_k3pmiu";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_hero2_2_chapte_k3pmiu" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_hero2_2_chapte_k3pmiu";
  ALTER TABLE "_regional_communities_v_blocks_hero2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_hero2_2_chapte_k3pmiu" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_hero2_2_chapte_k3pmiu";
  ALTER TABLE "_regional_communities_v_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_section_header_unitpz";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_section_header_unitpz" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_section_header_unitpz";
  ALTER TABLE "_regional_communities_v_blocks_section_header_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_section_header_unitpz" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_section_header_unitpz";
  ALTER TABLE "_regional_communities_v_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_split_row_2_ch_1cab6h9";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_split_row_2_ch_1cab6h9" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_split_row_2_ch_1cab6h9";
  ALTER TABLE "_regional_communities_v_blocks_split_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_split_row_2_ch_1cab6h9" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_split_row_2_ch_1cab6h9";
  ALTER TABLE "_regional_communities_v_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_carousel1_2_ch_hbqyvn";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_carousel1_2_ch_hbqyvn" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_carousel1_2_ch_hbqyvn";
  ALTER TABLE "_regional_communities_v_blocks_carousel1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_carousel1_2_ch_hbqyvn" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_carousel1_2_ch_hbqyvn";
  ALTER TABLE "_regional_communities_v_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_timeline_row_2_urw8y8";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_timeline_row_2_urw8y8" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_timeline_row_2_urw8y8";
  ALTER TABLE "_regional_communities_v_blocks_timeline_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_timeline_row_2_urw8y8" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_timeline_row_2_urw8y8";
  ALTER TABLE "_regional_communities_v_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_faqs_2_chapter_chapter_kind";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_faqs_2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_faqs_2_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_faqs_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_faqs_2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_faqs_2_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_content_feed_2_1gu2ali";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_content_feed_2_1gu2ali" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_content_feed_2_1gu2ali";
  ALTER TABLE "_regional_communities_v_blocks_content_feed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_content_feed_2_1gu2ali" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_content_feed_2_1gu2ali";
  ALTER TABLE "_regional_communities_v_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_events_calenda_bavpvo";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_events_calenda_bavpvo" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_events_calenda_bavpvo";
  ALTER TABLE "_regional_communities_v_blocks_events_calendar_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_events_calenda_bavpvo" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_events_calenda_bavpvo";
  ALTER TABLE "_regional_communities_v_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_people_widget__1ucyr60";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_people_widget__1ucyr60" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_people_widget__1ucyr60";
  ALTER TABLE "_regional_communities_v_blocks_people_widget_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_people_widget__1ucyr60" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_people_widget__1ucyr60";
  ALTER TABLE "_regional_communities_v_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_grid_row_2_cha_1lo9grh";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_grid_row_2_cha_1lo9grh" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_grid_row_2_cha_1lo9grh";
  ALTER TABLE "_regional_communities_v_blocks_grid_row_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_grid_row_2_cha_1lo9grh" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_grid_row_2_cha_1lo9grh";
  ALTER TABLE "_regional_communities_v_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_region_map_2_c_1als5o7";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_region_map_2_c_1als5o7" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_region_map_2_c_1als5o7";
  ALTER TABLE "_regional_communities_v_blocks_region_map_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_region_map_2_c_1als5o7" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_region_map_2_c_1als5o7";
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_2__13fttjj";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_2__13fttjj" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_atlas_embed_2__13fttjj";
  ALTER TABLE "_regional_communities_v_blocks_atlas_embed_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_atlas_embed_2__13fttjj" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_atlas_embed_2__13fttjj";
  ALTER TABLE "_regional_communities_v_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_cta1_2_chapter_chapter_kind";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_cta1_2_chapter_chapter_kind" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_cta1_2_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_cta1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_cta1_2_chapter_chapter_kind" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_cta1_2_chapter_chapter_kind";
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_1kwp65f";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_1kwp65f" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_submit_story_b_1kwp65f";
  ALTER TABLE "_regional_communities_v_blocks_submit_story_banner_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_submit_story_b_1kwp65f" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_submit_story_b_1kwp65f";
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_form_newslette_on6v9k";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_form_newslette_on6v9k" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_form_newslette_on6v9k";
  ALTER TABLE "_regional_communities_v_blocks_form_newsletter_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_form_newslette_on6v9k" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_form_newslette_on6v9k";
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_2__1g5s77c";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_2__1g5s77c" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_logo_cloud1_2__1g5s77c";
  ALTER TABLE "_regional_communities_v_blocks_logo_cloud1_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_logo_cloud1_2__1g5s77c" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_logo_cloud1_2__1g5s77c";
  ALTER TABLE "_regional_communities_v_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_carousel2_2_ch_18ei82w";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_carousel2_2_ch_18ei82w" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_carousel2_2_ch_18ei82w";
  ALTER TABLE "_regional_communities_v_blocks_carousel2_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_carousel2_2_ch_18ei82w" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_carousel2_2_ch_18ei82w";
  ALTER TABLE "_regional_communities_v_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DATA TYPE text;
  ALTER TABLE "_regional_communities_v_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__regional_communities_v_blocks_community_memb_16accr7";
  CREATE TYPE "public"."enum__regional_communities_v_blocks_community_memb_16accr7" AS ENUM('none', 'overview', 'agendas', 'caseStudies', 'news', 'voices', 'members', 'partners', 'custom');
  ALTER TABLE "_regional_communities_v_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DEFAULT 'none'::"public"."enum__regional_communities_v_blocks_community_memb_16accr7";
  ALTER TABLE "_regional_communities_v_blocks_community_members_2" ALTER COLUMN "chapter_kind" SET DATA TYPE "public"."enum__regional_communities_v_blocks_community_memb_16accr7" USING "chapter_kind"::"public"."enum__regional_communities_v_blocks_community_memb_16accr7";
  DROP INDEX "events_organiser_idx";
  ALTER TABLE "events" DROP COLUMN "origin";
  ALTER TABLE "events" DROP COLUMN "organiser_id";
  ALTER TABLE "events" DROP COLUMN "organiser_name";
  ALTER TABLE "events" DROP COLUMN "notified_status";
  DROP TYPE "public"."enum_events_origin";`)
}
