import { describe, it, expect } from "vitest";
import { sanitizeSvg } from "../sanitize-svg";

/**
 * The sanitizer is the trust boundary for every stored SVG (charts are
 * generated by us, mermaid SVGs are rendered in the author's browser and
 * posted back) — so it must strip active content while keeping the drawing
 * primitives mermaid and the chart generator actually use.
 */

describe("sanitize-svg: strips dangerous content", () => {
  it("strips <script> elements", () => {
    const out = sanitizeSvg('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script><rect width="10" height="10"/></svg>');
    expect(out).not.toBeNull();
    expect(out).not.toContain("script");
    expect(out).toContain("<rect");
  });

  it("strips event handler attributes (onload, onclick)", () => {
    const out = sanitizeSvg('<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"><circle r="5" onclick="steal()"/></svg>');
    expect(out).not.toBeNull();
    expect(out).not.toMatch(/on(load|click)/i);
    expect(out).toContain("<circle");
  });

  it("strips <foreignObject> (would allow arbitrary HTML inside the SVG)", () => {
    const out = sanitizeSvg(
      '<svg xmlns="http://www.w3.org/2000/svg"><foreignObject><iframe src="https://evil.example"></iframe></foreignObject><path d="M0 0L10 10"/></svg>'
    );
    expect(out).not.toBeNull();
    expect(out).not.toContain("foreignObject");
    expect(out).not.toContain("iframe");
    expect(out).toContain("<path");
  });

  it("strips external hrefs but keeps internal fragment references", () => {
    const out = sanitizeSvg(
      '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">' +
        '<a href="https://evil.example/phish"><text>click</text></a>' +
        '<use href="#marker"/></svg>'
    );
    expect(out).not.toBeNull();
    expect(out).not.toContain("evil.example");
    expect(out).toContain('href="#marker"');
  });

  it("strips javascript: URIs", () => {
    const out = sanitizeSvg(
      '<svg xmlns="http://www.w3.org/2000/svg"><a href="javascript:alert(1)"><text>x</text></a></svg>'
    );
    expect(out).not.toBeNull();
    expect(out).not.toContain("javascript:");
  });
});

describe("sanitize-svg: keeps legitimate drawing content", () => {
  it("keeps paths, rects, circles, text, groups and gridline classes", () => {
    const raw =
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400" role="img" aria-labelledby="t d">' +
      '<title id="t">Chart</title><desc id="d">Bar chart, 2 items, total 3.</desc>' +
      '<g><line class="grid" x1="0" y1="10" x2="640" y2="10"/>' +
      '<rect class="bar" x="10" y="10" width="40" height="80" fill="#4186C3"/>' +
      '<circle class="dot" cx="5" cy="5" r="3"/>' +
      '<path class="slice" d="M0 0 A 10 10 0 0 1 10 10 Z"/>' +
      "<text>MENA</text></g></svg>";
    const out = sanitizeSvg(raw);
    expect(out).not.toBeNull();
    for (const keep of ["<title", "<desc", "<line", "<rect", "<circle", "<path", "<text", 'class="bar"']) {
      expect(out).toContain(keep);
    }
  });

  it("keeps <style> and marker refs (mermaid relies on both)", () => {
    const raw =
      '<svg xmlns="http://www.w3.org/2000/svg"><style>.edge{stroke:#333}</style>' +
      '<defs><marker id="arrow"><path d="M0,0 L10,5"/></marker></defs>' +
      '<path class="edge" marker-end="url(#arrow)" d="M0 0L50 50"/></svg>';
    const out = sanitizeSvg(raw);
    expect(out).not.toBeNull();
    expect(out).toContain("<style");
    expect(out).toContain("marker-end");
  });
});

describe("sanitize-svg: rejects non-SVG input", () => {
  it("returns null for empty / non-string input", () => {
    expect(sanitizeSvg("")).toBeNull();
    expect(sanitizeSvg(undefined as unknown as string)).toBeNull();
    expect(sanitizeSvg(42 as unknown as string)).toBeNull();
  });

  it("returns null when nothing SVG survives sanitization", () => {
    expect(sanitizeSvg("<div>not an svg</div>")).toBeNull();
    expect(sanitizeSvg("<script>alert(1)</script>")).toBeNull();
  });

  it("returns null for oversized payloads", () => {
    const huge = `<svg xmlns="http://www.w3.org/2000/svg">${"<rect/>".repeat(400_000)}</svg>`;
    expect(sanitizeSvg(huge)).toBeNull();
  });
});
