import { RegionCode } from "./region-codes";

/**
 * ISO-3166 alpha-3 → UN-M49 SDG region. Source: the UN M49 standard
 * (https://unstats.un.org/unsd/methodology/m49/). Every UN member/observer with
 * a land polygon is assigned to exactly one of the 7 SDG regions. Antarctica
 * (ATA) and uninhabited territories are intentionally omitted (→ null).
 *
 * Notes on a few M49 placements that surprise people:
 *  - Cyprus (CYP), Armenia (ARM), Azerbaijan (AZE), Georgia (GEO) → Western Asia
 *    → NORTHERN_AFRICA_AND_WESTERN_ASIA.
 *  - Iran (IRN) → Southern Asia → CENTRAL_AND_SOUTHERN_ASIA.
 *  - Russia (RUS) → Eastern Europe → EUROPE_AND_NORTH_AMERICA.
 *  - Greenland (GRL) → Northern America → EUROPE_AND_NORTH_AMERICA.
 *  - Sudan (SDN) → Sub-Saharan Africa; the rest of N. Africa (DZA/EGY/LBY/MAR/TUN)
 *    → NORTHERN_AFRICA_AND_WESTERN_ASIA.
 */
export const REGION_MEMBERSHIP: Record<string, RegionCode> = {
  // ---- Sub-Saharan Africa ----------------------------------------------------
  AGO: "SUB_SAHARAN_AFRICA", BEN: "SUB_SAHARAN_AFRICA", BWA: "SUB_SAHARAN_AFRICA",
  BFA: "SUB_SAHARAN_AFRICA", BDI: "SUB_SAHARAN_AFRICA", CPV: "SUB_SAHARAN_AFRICA",
  CMR: "SUB_SAHARAN_AFRICA", CAF: "SUB_SAHARAN_AFRICA", TCD: "SUB_SAHARAN_AFRICA",
  COM: "SUB_SAHARAN_AFRICA", COG: "SUB_SAHARAN_AFRICA", COD: "SUB_SAHARAN_AFRICA",
  CIV: "SUB_SAHARAN_AFRICA", DJI: "SUB_SAHARAN_AFRICA", GNQ: "SUB_SAHARAN_AFRICA",
  ERI: "SUB_SAHARAN_AFRICA", SWZ: "SUB_SAHARAN_AFRICA", ETH: "SUB_SAHARAN_AFRICA",
  GAB: "SUB_SAHARAN_AFRICA", GMB: "SUB_SAHARAN_AFRICA", GHA: "SUB_SAHARAN_AFRICA",
  GIN: "SUB_SAHARAN_AFRICA", GNB: "SUB_SAHARAN_AFRICA", KEN: "SUB_SAHARAN_AFRICA",
  LSO: "SUB_SAHARAN_AFRICA", LBR: "SUB_SAHARAN_AFRICA", MDG: "SUB_SAHARAN_AFRICA",
  MWI: "SUB_SAHARAN_AFRICA", MLI: "SUB_SAHARAN_AFRICA", MRT: "SUB_SAHARAN_AFRICA",
  MUS: "SUB_SAHARAN_AFRICA", MOZ: "SUB_SAHARAN_AFRICA", NAM: "SUB_SAHARAN_AFRICA",
  NER: "SUB_SAHARAN_AFRICA", NGA: "SUB_SAHARAN_AFRICA", RWA: "SUB_SAHARAN_AFRICA",
  STP: "SUB_SAHARAN_AFRICA", SEN: "SUB_SAHARAN_AFRICA", SYC: "SUB_SAHARAN_AFRICA",
  SLE: "SUB_SAHARAN_AFRICA", SOM: "SUB_SAHARAN_AFRICA", ZAF: "SUB_SAHARAN_AFRICA",
  SSD: "SUB_SAHARAN_AFRICA", SDN: "SUB_SAHARAN_AFRICA", TGO: "SUB_SAHARAN_AFRICA",
  TZA: "SUB_SAHARAN_AFRICA", UGA: "SUB_SAHARAN_AFRICA", ZMB: "SUB_SAHARAN_AFRICA",
  ZWE: "SUB_SAHARAN_AFRICA",

  // ---- Northern Africa and Western Asia --------------------------------------
  DZA: "NORTHERN_AFRICA_AND_WESTERN_ASIA", EGY: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  LBY: "NORTHERN_AFRICA_AND_WESTERN_ASIA", MAR: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  TUN: "NORTHERN_AFRICA_AND_WESTERN_ASIA", ESH: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  ARM: "NORTHERN_AFRICA_AND_WESTERN_ASIA", AZE: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  BHR: "NORTHERN_AFRICA_AND_WESTERN_ASIA", CYP: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  GEO: "NORTHERN_AFRICA_AND_WESTERN_ASIA", IRQ: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  ISR: "NORTHERN_AFRICA_AND_WESTERN_ASIA", JOR: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  KWT: "NORTHERN_AFRICA_AND_WESTERN_ASIA", LBN: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  OMN: "NORTHERN_AFRICA_AND_WESTERN_ASIA", PSE: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  QAT: "NORTHERN_AFRICA_AND_WESTERN_ASIA", SAU: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  SYR: "NORTHERN_AFRICA_AND_WESTERN_ASIA", TUR: "NORTHERN_AFRICA_AND_WESTERN_ASIA",
  ARE: "NORTHERN_AFRICA_AND_WESTERN_ASIA", YEM: "NORTHERN_AFRICA_AND_WESTERN_ASIA",

  // ---- Central and Southern Asia ---------------------------------------------
  KAZ: "CENTRAL_AND_SOUTHERN_ASIA", KGZ: "CENTRAL_AND_SOUTHERN_ASIA",
  TJK: "CENTRAL_AND_SOUTHERN_ASIA", TKM: "CENTRAL_AND_SOUTHERN_ASIA",
  UZB: "CENTRAL_AND_SOUTHERN_ASIA", AFG: "CENTRAL_AND_SOUTHERN_ASIA",
  BGD: "CENTRAL_AND_SOUTHERN_ASIA", BTN: "CENTRAL_AND_SOUTHERN_ASIA",
  IND: "CENTRAL_AND_SOUTHERN_ASIA", IRN: "CENTRAL_AND_SOUTHERN_ASIA",
  MDV: "CENTRAL_AND_SOUTHERN_ASIA", NPL: "CENTRAL_AND_SOUTHERN_ASIA",
  PAK: "CENTRAL_AND_SOUTHERN_ASIA", LKA: "CENTRAL_AND_SOUTHERN_ASIA",

  // ---- Eastern and South-Eastern Asia ----------------------------------------
  CHN: "EASTERN_AND_SOUTH_EASTERN_ASIA", PRK: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  JPN: "EASTERN_AND_SOUTH_EASTERN_ASIA", MNG: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  KOR: "EASTERN_AND_SOUTH_EASTERN_ASIA", TWN: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  BRN: "EASTERN_AND_SOUTH_EASTERN_ASIA", KHM: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  IDN: "EASTERN_AND_SOUTH_EASTERN_ASIA", LAO: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  MYS: "EASTERN_AND_SOUTH_EASTERN_ASIA", MMR: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  PHL: "EASTERN_AND_SOUTH_EASTERN_ASIA", SGP: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  THA: "EASTERN_AND_SOUTH_EASTERN_ASIA", TLS: "EASTERN_AND_SOUTH_EASTERN_ASIA",
  VNM: "EASTERN_AND_SOUTH_EASTERN_ASIA",

  // ---- Latin America and the Caribbean ---------------------------------------
  ATG: "LATIN_AMERICA_AND_THE_CARIBBEAN", ARG: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  BHS: "LATIN_AMERICA_AND_THE_CARIBBEAN", BRB: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  BLZ: "LATIN_AMERICA_AND_THE_CARIBBEAN", BOL: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  BRA: "LATIN_AMERICA_AND_THE_CARIBBEAN", CHL: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  COL: "LATIN_AMERICA_AND_THE_CARIBBEAN", CRI: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  CUB: "LATIN_AMERICA_AND_THE_CARIBBEAN", DMA: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  DOM: "LATIN_AMERICA_AND_THE_CARIBBEAN", ECU: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  SLV: "LATIN_AMERICA_AND_THE_CARIBBEAN", GRD: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  GTM: "LATIN_AMERICA_AND_THE_CARIBBEAN", GUY: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  HTI: "LATIN_AMERICA_AND_THE_CARIBBEAN", HND: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  JAM: "LATIN_AMERICA_AND_THE_CARIBBEAN", MEX: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  NIC: "LATIN_AMERICA_AND_THE_CARIBBEAN", PAN: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  PRY: "LATIN_AMERICA_AND_THE_CARIBBEAN", PER: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  KNA: "LATIN_AMERICA_AND_THE_CARIBBEAN", LCA: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  VCT: "LATIN_AMERICA_AND_THE_CARIBBEAN", SUR: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  TTO: "LATIN_AMERICA_AND_THE_CARIBBEAN", URY: "LATIN_AMERICA_AND_THE_CARIBBEAN",
  VEN: "LATIN_AMERICA_AND_THE_CARIBBEAN",

  // ---- Oceania ---------------------------------------------------------------
  AUS: "OCEANIA", NZL: "OCEANIA", FJI: "OCEANIA", PNG: "OCEANIA",
  SLB: "OCEANIA", VUT: "OCEANIA", FSM: "OCEANIA", KIR: "OCEANIA",
  MHL: "OCEANIA", NRU: "OCEANIA", PLW: "OCEANIA", WSM: "OCEANIA",
  TON: "OCEANIA", TUV: "OCEANIA",

  // ---- Europe and North America ----------------------------------------------
  ALB: "EUROPE_AND_NORTH_AMERICA", AND: "EUROPE_AND_NORTH_AMERICA",
  AUT: "EUROPE_AND_NORTH_AMERICA", BLR: "EUROPE_AND_NORTH_AMERICA",
  BEL: "EUROPE_AND_NORTH_AMERICA", BIH: "EUROPE_AND_NORTH_AMERICA",
  BGR: "EUROPE_AND_NORTH_AMERICA", HRV: "EUROPE_AND_NORTH_AMERICA",
  CZE: "EUROPE_AND_NORTH_AMERICA", DNK: "EUROPE_AND_NORTH_AMERICA",
  EST: "EUROPE_AND_NORTH_AMERICA", FIN: "EUROPE_AND_NORTH_AMERICA",
  FRA: "EUROPE_AND_NORTH_AMERICA", DEU: "EUROPE_AND_NORTH_AMERICA",
  GRC: "EUROPE_AND_NORTH_AMERICA", HUN: "EUROPE_AND_NORTH_AMERICA",
  ISL: "EUROPE_AND_NORTH_AMERICA", IRL: "EUROPE_AND_NORTH_AMERICA",
  ITA: "EUROPE_AND_NORTH_AMERICA", XKX: "EUROPE_AND_NORTH_AMERICA",
  LVA: "EUROPE_AND_NORTH_AMERICA", LIE: "EUROPE_AND_NORTH_AMERICA",
  LTU: "EUROPE_AND_NORTH_AMERICA", LUX: "EUROPE_AND_NORTH_AMERICA",
  MLT: "EUROPE_AND_NORTH_AMERICA", MDA: "EUROPE_AND_NORTH_AMERICA",
  MCO: "EUROPE_AND_NORTH_AMERICA", MNE: "EUROPE_AND_NORTH_AMERICA",
  NLD: "EUROPE_AND_NORTH_AMERICA", MKD: "EUROPE_AND_NORTH_AMERICA",
  NOR: "EUROPE_AND_NORTH_AMERICA", POL: "EUROPE_AND_NORTH_AMERICA",
  PRT: "EUROPE_AND_NORTH_AMERICA", ROU: "EUROPE_AND_NORTH_AMERICA",
  RUS: "EUROPE_AND_NORTH_AMERICA", SMR: "EUROPE_AND_NORTH_AMERICA",
  SRB: "EUROPE_AND_NORTH_AMERICA", SVK: "EUROPE_AND_NORTH_AMERICA",
  SVN: "EUROPE_AND_NORTH_AMERICA", ESP: "EUROPE_AND_NORTH_AMERICA",
  SWE: "EUROPE_AND_NORTH_AMERICA", CHE: "EUROPE_AND_NORTH_AMERICA",
  UKR: "EUROPE_AND_NORTH_AMERICA", GBR: "EUROPE_AND_NORTH_AMERICA",
  VAT: "EUROPE_AND_NORTH_AMERICA", CAN: "EUROPE_AND_NORTH_AMERICA",
  USA: "EUROPE_AND_NORTH_AMERICA", GRL: "EUROPE_AND_NORTH_AMERICA",
};

export function isoToRegion(iso3: string): RegionCode | null {
  return REGION_MEMBERSHIP[iso3] ?? null;
}
