export { default as ProfileHeaderBlock } from './profile-header-block'
export { default as BasicInfoBlock } from './basic-info-block'
export { default as WorkDetailsBlock } from './work-details-block'
export { default as RecentWorkBlock } from './recent-work-block'
export { default as CommunityHubBlock } from './community-hub-block'
export { default as SocialLinksBlock } from './social-links-block'
