import createDOMPurify from "dompurify";
import { JSDOM } from "jsdom";

/**
 * Server-side SVG sanitizer — the trust boundary for every SVG stored on a
 * "Data & story" block (Task E8).
 *
 * Two kinds of SVG cross it:
 *  - chart SVGs generated by our own renderChartSvg (defense in depth), and
 *  - mermaid SVGs rendered in the AUTHOR'S browser and posted back to
 *    /api/story-blocks/render — i.e. fully attacker-controllable input.
 *
 * Implementation: dompurify driven by a jsdom window (both direct deps; this
 * module is server-only). A dedicated instance — NOT a shared singleton — so
 * the fragment-only href hook below can't leak into any other sanitization
 * the app might do.
 *
 * Profile: DOMPurify's SVG profile, additionally:
 *  - foreignObject/script forbidden (foreignObject would smuggle arbitrary
 *    HTML; mermaid is configured with htmlLabels:false so it never needs it),
 *  - href/xlink:href restricted to same-document fragments (`#…`) via an
 *    uponSanitizeAttribute hook — kills external and javascript: references
 *    while keeping mermaid's internal marker/use refs. (Deliberately a hook,
 *    not ALLOWED_URI_REGEXP: that option is matched against EVERY attribute
 *    value, which would strip path `d`/`marker-end` data too.)
 *  - <style> kept (mermaid themes its diagrams through an inline stylesheet;
 *    DOMPurify still sanitizes the CSS body), <use> re-allowed for the same
 *    reason — safe once hrefs are fragment-only.
 */

const MAX_SVG_BYTES = 1_500_000; // ~1.5MB — generous for diagrams, blocks abuse.

const purify = createDOMPurify(new JSDOM("").window);

// Fragment-only URI policy for the SVG profile: any href-like attribute must
// point inside the document itself.
purify.addHook("uponSanitizeAttribute", (_node, data) => {
  const name = data.attrName.toLowerCase();
  if (name === "href" || name === "xlink:href" || name === "src") {
    if (!data.attrValue.startsWith("#")) data.keepAttr = false;
  }
});

export function sanitizeSvg(raw: string): string | null {
  if (typeof raw !== "string" || raw.trim().length === 0) return null;
  if (raw.length > MAX_SVG_BYTES) return null;

  const sanitized = purify.sanitize(raw, {
    USE_PROFILES: { svg: true, svgFilters: true },
    ADD_TAGS: ["style", "use"],
    FORBID_TAGS: ["foreignObject", "script", "iframe", "object", "embed"],
  });

  const trimmed = sanitized.trim();
  // Reject anything that didn't survive as an actual SVG document (plain
  // HTML input, script-only input, empty output).
  if (!trimmed.toLowerCase().startsWith("<svg")) return null;
  return trimmed;
}
