import { groq } from "next-sanity";

// @sanity-typegen-ignore
export const gridAgendaQuery = groq`
  _type == "grid-agenda" => {
    _type,
    _key,
    showTags,
    showDownloadButtons,
    showMetadata,
    agenda->{
      _id,
      title,
      subtitle,
      description,
      slug,
      agendaType,
      year,
      publishDate,
      totalDownloadCount,
      featured,
      accessLevel,
      coverImage{
        asset->{
          _id,
          url,
          mimeType,
          metadata {
            lqip,
            dimensions {
              width,
              height
            }
          }
        },
        hotspot,
        crop,
        alt
      },
      files[]{
        language,
        file{
          asset->{
            _id,
            url,
            originalFilename,
            size,
            mimeType
          }
        },
        downloadCount,
        lastDownloaded
      },
      tags[]->{
        _id,
        label,
        value,
        color,
        category
      },
      organizations[]->{
        _id,
        name,
        slug,
        acronym,
        logo{
          asset->{
            _id,
            url
          },
          alt
        }
      },
      regionalCommunities[]->{
        _id,
        name,
        slug,
        code
      }
    }
  }
`;